title: CMIP6 Data Hackathon
menu_title: CMIP6 Data Hack<span class="hide-very-narrow">athon</span><br><small><span class="hide-very-narrow">in association</span> with the Met Office & Bristol</small>
author: University of Bristol Jean Golding Institute & Cabot Institute, 
  Met Office Academic Partnership
description:
  The Met Office Academic Partnership is a cluster of research excellence that
  brings together the Met Office and leaders in weather and climate science
  (Universities of [Bristol](https://www.bristol.ac.uk),
  [Exeter](https://www.exeter.ac.uk), [Leeds](https://www.leeds.ac.uk),
  [Oxford](https://www.ox.ac.uk) and [Reading](https://www.reading.ac.uk) and
  [UCL](https://www.ucl.ac.uk)). [More info](/about/#the-met-office-academic-partnership).
url: "https://cmip6moap.github.io"
github_username: cmip6moap 
theme: minima
header_pages:
  - registration.md
  - projects.md
  - agenda.md
  - resources.md
  - about.md
