title: UCL UKCP Hackathon
menu_title: UCL UKCP Hack<span class="hide-very-narrow">athon</span><br><small><span class="hide-very-narrow">with</span> UCL, Met Office</small>
author: University College London, 
  Met Office Academic Partnership
description:
  The MOAP CMIP6 Hackathon is a 3-day hackathon event, organised by the
  University of Bristol’s Jean Golding Institute and Cabot Institute. Over the
  course of the event, teams of academic researchers from across the UK will
  work on research questions set by the MOAP partners related to earth-system
  science and CMIP6 data.
url: "https://cmip6moap.github.io"
github_username: cmip6moap 
theme: minima
header_pages:
  - registration.md
  - projects.md
  - agenda.md
  - resources.md
  - about.md
